//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerumDesk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:saperatec01.database.windows.net,1433;Initial Catalog=VerumTest;Persis" +
            "t Security Info=False;User ID=azureadmin;Password=U327Shns\r\n;MultipleActiveResul" +
            "tSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")]
        public string DBConnectionTest {
            get {
                return ((string)(this["DBConnectionTest"]));
            }
            set {
                this["DBConnectionTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:saperatec01.database.windows.net,1433;Initial Catalog=VerumProd;Persis" +
            "t Security Info=False;User ID=azureadmin;Password=U327Shns\r\n;MultipleActiveResul" +
            "tSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")]
        public string DBConnectionAlternative {
            get {
                return ((string)(this["DBConnectionAlternative"]));
            }
            set {
                this["DBConnectionAlternative"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f7c847da-18a7-41ee-a04c-8c4d57ae29cf")]
        public string AzureClientId {
            get {
                return ((string)(this["AzureClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOD8Q~oFLz.0RzzJUbPakKFcsv5c6Asob-A8oaPZ")]
        public string AzureSecret {
            get {
                return ((string)(this["AzureSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7b529929-46de-4b14-8cec-8d0d154e2f0a")]
        public string AzureTenantId {
            get {
                return ((string)(this["AzureTenantId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/token")]
        public string MicrosoftLoginUrlToken {
            get {
                return ((string)(this["MicrosoftLoginUrlToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.businesscentral.dynamics.com/v2.0/{TenantId}/{Environment}/ODataV4/Co" +
            "mpany(\'{CompanyName}\')/{EndPoint}")]
        public string Dynamic365BCCompanyDataUrl {
            get {
                return ((string)(this["Dynamic365BCCompanyDataUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:saperatec01.database.windows.net,1433;Initial Catalog=VerumProd;Persis" +
            "t Security Info=False;User ID=azureadmin;Password=\r\n;MultipleActiveResultSets=Fa" +
            "lse;Encrypt=True;TrustServerCertificate=False;Connection Timeout=120;")]
        public string DBConnectionProduction {
            get {
                return ((string)(this["DBConnectionProduction"]));
            }
            set {
                this["DBConnectionProduction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = TECHCOMPILER-67; Initial Catalog = VerumTest; Integrated Security =" +
            " True")]
        public string DBConnectionDevelop {
            get {
                return ((string)(this["DBConnectionDevelop"]));
            }
            set {
                this["DBConnectionDevelop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:7226")]
        public string VerumAPIBaseUrl {
            get {
                return ((string)(this["VerumAPIBaseUrl"]));
            }
            set {
                this["VerumAPIBaseUrl"] = value;
            }
        }
    }
}
