//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerumBusinessObjects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerumBusinessObjects.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative amount cannot be assigned to a book record..
        /// </summary>
        internal static string BookRecordAssignedNegativeAmount {
            get {
                return ResourceManager.GetString("BookRecordAssignedNegativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data value assigned to a business object is not valid..
        /// </summary>
        internal static string BusinessObjectAssignedInvalidValue {
            get {
                return ResourceManager.GetString("BusinessObjectAssignedInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use invalid client id..
        /// </summary>
        internal static string ClientInvalidClientID {
            get {
                return ResourceManager.GetString("ClientInvalidClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction applies a currency exchange rate which is not specified for the transaction date..
        /// </summary>
        internal static string CurrencyExchangeRateNotAvailable {
            get {
                return ResourceManager.GetString("CurrencyExchangeRateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no definition of a default advance received account for the current client..
        /// </summary>
        internal static string PlanAccountFunctionAdvanceReceivedDefaultNotDefined {
            get {
                return ResourceManager.GetString("PlanAccountFunctionAdvanceReceivedDefaultNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no definition of a default cash account for the current client..
        /// </summary>
        internal static string PlanAccountFunctionCashDefaultNotDefined {
            get {
                return ResourceManager.GetString("PlanAccountFunctionCashDefaultNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no definition of a default payables account for the current client..
        /// </summary>
        internal static string PlanAccountFunctionPayablesDefaultNotDefined {
            get {
                return ResourceManager.GetString("PlanAccountFunctionPayablesDefaultNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book records of baseline status cannot be deleted or updated.
        /// </summary>
        internal static string PlanBaselineRecordsAreProtected {
            get {
                return ResourceManager.GetString("PlanBaselineRecordsAreProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected plan has been applied to baseline and is therefore protected. Copy the plan for changes and reimplementation..
        /// </summary>
        internal static string PlanCannotImplementWhenBaseline {
            get {
                return ResourceManager.GetString("PlanCannotImplementWhenBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan element item for plan element instance not found. Inconsistent database..
        /// </summary>
        internal static string PlanItemNotFound {
            get {
                return ResourceManager.GetString("PlanItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create user with invalid name, login or password.
        /// </summary>
        internal static string UserCreateInvalidCredentials {
            get {
                return ResourceManager.GetString("UserCreateInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to use invalid user type (standard, admin, ...).
        /// </summary>
        internal static string UserInvalidUserType {
            get {
                return ResourceManager.GetString("UserInvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requires admin rights for current operation..
        /// </summary>
        internal static string UserNoAdminRights {
            get {
                return ResourceManager.GetString("UserNoAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login is not correct.
        /// </summary>
        internal static string UserUnknownLogin {
            get {
                return ResourceManager.GetString("UserUnknownLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATBalance Account not defined without reverse charge.
        /// </summary>
        internal static string VATRuleVATBalanceNotDefined {
            get {
                return ResourceManager.GetString("VATRuleVATBalanceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to connect to expired session key.
        /// </summary>
        internal static string VerumExpiredSessionKey {
            get {
                return ResourceManager.GetString("VerumExpiredSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to connect to invalid session key.
        /// </summary>
        internal static string VerumInvalidSessionKey {
            get {
                return ResourceManager.GetString("VerumInvalidSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to access Verum without valid session.
        /// </summary>
        internal static string VerumNoSessionAvailable {
            get {
                return ResourceManager.GetString("VerumNoSessionAvailable", resourceCulture);
            }
        }
    }
}
