//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerumBusinessObjects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerumBusinessObjects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanzlei-Rechnungswesen.
        /// </summary>
        internal static string DATEVJournalUniqueID1 {
            get {
                return ResourceManager.GetString("DATEVJournalUniqueID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string DATEVJournalUniqueID2 {
            get {
                return ResourceManager.GetString("DATEVJournalUniqueID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfjournal.
        /// </summary>
        internal static string DATEVJournalUniqueID3 {
            get {
                return ResourceManager.GetString("DATEVJournalUniqueID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=tcp:mysqlserver1726981181.database.windows.net,1433;Initial Catalog=VerumDBDev;Persist Security Info=False;User ID=ThorstenHornung;Password=ks83sTO_p; MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;.
        /// </summary>
        internal static string VerumDBConnectionStringDevelop {
            get {
                return ResourceManager.GetString("VerumDBConnectionStringDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source = SAP-26\SQLEXPRESS; Initial Catalog = VerumDB; Integrated Security = True.
        /// </summary>
        internal static string VerumDBConnectionStringLocal {
            get {
                return ResourceManager.GetString("VerumDBConnectionStringLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=tcp:saperatec01.database.windows.net,1433;Initial Catalog=VerumProd;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication=&quot;Active Directory Integrated&quot;;.
        /// </summary>
        internal static string VerumDBConnectionStringProduction {
            get {
                return ResourceManager.GetString("VerumDBConnectionStringProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string VerumMaximumSessionTime {
            get {
                return ResourceManager.GetString("VerumMaximumSessionTime", resourceCulture);
            }
        }
    }
}
